export const surpriseMePrompts = [
  'a floating city in the clouds, digital art',
  'a group of talking animals having a tea party, watercolor painting',
  'a magical forest with glowing mushrooms and fireflies, digital illustration',
  'a steampunk-inspired underwater submarine, 3D render',
  'a time-traveling robot exploring ancient ruins, mixed media collage',
  'a celestial landscape with planets and galaxies made of candy, digital art',
  'a whimsical carousel filled with mythical creatures, oil painting',
  'a futuristic cityscape with flying cars and holographic billboards, concept art',
  'a mermaid playing the violin on a moonlit beach, acrylic painting',
  'a surreal garden with oversized flowers and talking animals, mixed media',
  'a cyberpunk-inspired city skyline at night, neon lights photography',
  'a fantastical creature made of mechanical parts and organic elements, digital sculpture',
  'a haunted mansion in a misty graveyard, ink drawing',
  'a rainbow-colored waterfall flowing through a lush jungle, digital painting',
  'a whimsical teapot with legs and arms, ceramic sculpture',
  'a futuristic space station orbiting a distant planet, concept art',
  'a group of friendly monsters having a dance party, children\'s book illustration',
  'a magical book that opens to reveal a portal to another world, mixed media',
  'a floating island with gravity-defying architecture, architectural rendering',
  'a mythical phoenix rising from the ashes, digital manipulation',
  'an enchanted forest with glowing fireflies and hidden fairy doors, watercolor',
  'a futuristic robot chef cooking a gourmet meal, digital illustration',
  'a mysterious door at the end of a long corridor, charcoal drawing',
  'a rainbow-colored zebra grazing in a field of flowers, pastel painting',
  'a surrealistic landscape with melting clocks and floating objects, oil painting',
  'an underwater city inhabited by mermaids and sea creatures, concept art',
  'a whimsical hot air balloon festival in the sky, mixed media collage',
  'a magical potion bottle with swirling colors and sparkling effects, digital art',
  'a steampunk-inspired mechanical dragon soaring through the clouds, sculpture',
  'a secret garden filled with talking animals and enchanted plants, acrylic painting',
  'a futuristic cyborg exploring a post-apocalyptic city, digital manipulation',
  'a whimsical tea party in the middle of a meadow, watercolor illustration',
  'a mysterious portal leading to a parallel universe, mixed media collage',
  'a celestial constellation made of neon lights, night photography',
  'an enchanted castle on a floating island, oil painting',
  'a futuristic space colony with domed cities and advanced technology, concept art',
  'a mystical unicorn galloping through a field of wildflowers, pastel drawing',
  'a surrealistic portrait with distorted features and dreamlike elements, digital art',
  'an underwater scene with colorful coral reefs and exotic fish, watercolor painting',
  'a whimsical treehouse nestled among giant mushrooms, mixed media illustration',
  'a cyberpunk-inspired street scene with neon signs and futuristic vehicles, digital painting',
  'a mythical creature made of stars and galaxies, cosmic art',
  'a haunted forest with ghostly figures and eerie mist, charcoal drawing',
  'a rainbow-colored butterfly emerging from a cocoon, pastel painting',
  'a surreal landscape with floating islands and upside-down houses, oil painting',
  'an underwater shipwreck inhabited by mermaids and sea creatures, concept art',
  'a whimsical circus with acrobats, clowns, and fire breathers, mixed media collage',
  'a magical forest clearing with a hidden fairy village, acrylic painting',
  'a futuristic city skyline at sunset, illuminated by holographic displays, digital manipulation',
  'a whimsical garden with talking animals and singing flowers, watercolor illustration',
  'a mysterious door in the middle of a dense forest, leading to another dimension, mixed media collage',
  'a constellation of glowing jellyfish in a night sky, long-exposure photography',
  'an enchanted castle floating in the clouds, oil painting',
  'a futuristic spaceport with spaceships docking and launching, concept art',
  'a mythical dragon flying through a stormy sky, pastel drawing',
  'a surrealistic self-portrait with symbolic elements and hidden meanings, digital art',
  'an underwater scene with a sunken treasure chest and curious sea creatures, watercolor painting',
  'a whimsical village inhabited by talking animals, gnome houses, and fairy lights, mixed media illustration',
  'a cyberpunk-inspired alleyway with rain-soaked streets and glowing neon signs, digital painting',
  'a cosmic landscape with galaxies, nebulae, and a majestic supernova, space art',
  'a haunted mansion at twilight, shrouded in mystery and ghostly apparitions, charcoal drawing',
  'a vibrant peacock displaying its colorful feathers, pastel painting',
  'a surreal cityscape with buildings made of books and floating staircases, oil painting',
  'an underwater kingdom ruled by a mermaid queen, surrounded by loyal sea creatures, concept art',
  'a whimsical carnival with carousel rides, roller coasters, and cotton candy stands, mixed media collage',
  'a magical forest with glowing mushrooms, shimmering fireflies, and playful fairies, acrylic painting',
  'a futuristic city skyline with flying cars and bustling futuristic life, digital manipulation',
  'a whimsical tea party with mismatched teacups, talking animals, and enchanted treats, watercolor illustration',
  'a hidden cave entrance with ancient symbols and glowing crystals, mixed media collage',
  'a celestial night sky filled with constellations and shooting stars, astrophotography',
  'an enchanted castle nestled in a lush valley, surrounded by blooming flowers, oil painting',
  'a futuristic space station orbiting a distant planet, with spaceships docking and launching, concept art',
  'a mythical unicorn galloping through a rainbow-colored sky, pastel drawing',
  'a surrealistic self-portrait with a blend of organic and mechanical elements, digital art',
  'an underwater scene with vibrant coral reefs, exotic marine life, and sunken shipwrecks, watercolor painting',
  'a whimsical village hidden in the treetops, accessible only by magical bridges, mixed media illustration',
  'a cyberpunk-inspired city skyline at night, illuminated by holographic billboards and neon lights, digital painting',
  'a cosmic journey through a wormhole, passing through different dimensions, space art',
  'a haunted forest with twisted trees, misty paths, and glowing eyes peering from the darkness, charcoal drawing',
  'a colorful peacock displaying its magnificent plumage, surrounded by flowers, pastel painting',
  'a surrealistic landscape with floating islands, upside-down waterfalls, and gravity-defying architecture, oil painting',
  ];